name: Test

on: [push]

jobs:

  test:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python: [ '3.6', '3.7', '3.8', '3.9' ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'

    - name: Install dependencies
      run: python -m pip install -U pip setuptools
      run: pip install poetry
      run: poetry install

    - name: Start server
      run: poetry run python -m script.build_model
      run: poetry run gunicorn service.app:app -c ./gunicorn.py --worker-connections 100

    - name: Simple test connection by CURL
      run: curl -X POST -F "word=toys" -F "topn=20" localhost:8080/most-similar | echo
